#!/usr/bin/env ruby

require "pry"
require "escobar"

client = Escobar::Client.from_environment

client.app_names.sort.each do |name|
  pipeline = client[name]
  puts "#{name}:"
  pipeline.couplings.each do |environment|
    puts "  #{environment.name}: #{environment.app.name}"
  end
end
